INSERT INTO `SYS_USER` VALUES (1, 'admin', '$2a$10$oKoI7Y/Jgqt/qI/epsbYLO5F9eMZh2LebOs8/l5uZ4EDLhxAMpG3O');
INSERT INTO `SYS_USER` VALUES (2, 'normal', '$2a$10$jTDivURoJCXfj/KblvnRKu/7blXtUPnCTxaHlmcVHDR1NPXOaKpjC');


INSERT INTO `SYS_ROLE` VALUES (1, 'ROLE_ADMIN');
INSERT INTO `SYS_ROLE` VALUES (2, 'ROLE_NORMAL');

INSERT INTO `SYS_USER_ROLE` VALUES (1, 1);
INSERT INTO `SYS_USER_ROLE` VALUES (2, 2);


INSERT INTO `SYS_AUTHORITY` VALUES (1, '/test/a');
INSERT INTO `SYS_AUTHORITY` VALUES (2, '/test/b');

INSERT INTO `SYS_USER_AUTHORITY` VALUES (1, 1);
INSERT INTO `SYS_USER_AUTHORITY` VALUES (1, 2);
INSERT INTO `SYS_USER_AUTHORITY` VALUES (2, 2);

