spring:
  redis:
    database: 0
    host: localhost
    port: 6779
#    password: 123456
    # jedis is the default in springboot 1.x.x
    jedis:
      pool:
        max-active: 50
        max-wait: 2000ms            # max wait time try getting a connection, bellow zero means wait forever
        max-idle: 20
        min-idle: 5
    # Lettuce is based on netty
    lettuce:
      pool:
        max-active: 600
        max-wait: 2000ms
        max-idle: 300
        min-idle: 0
    timeout: 30000ms                # time out try connecting redis server


logging:
  file:
    name: test.log
    path: ${user.dir}
  level:
    com.acrobat.study.lock: info
