server:
    port: 8100
    servlet:
        context-path: /mybatisplus3

spring:
    application:
        name: mybatisplus3

    datasource:
        druid:
            driverClassName: org.h2.Driver
#            url:  jdbc:h2:${user.dir}/h2/mp3
            url:  jdbc:h2:mem:mp3
            username: root
            password: ayufan
            initialSize: 5
            minIdle: 5
            maxActive: 20
            maxWait: 60000                                # 获取连接的超时等待时间
            timeBetweenEvictionRunsMillis: 60000          # 检查要关闭的空闲连接
            min-evictableIdleTimeMillis: 30000            # 连接空闲多久后关闭
            validationQuery: SELECT 1                     # 检查是否可用
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true

        # 初始化SQL
        schema: classpath:sql/schema.sql
        data: classpath:sql/data.sql
    h2:
      console:
        enabled: true                                     # 开启控制台
        path: /h2                                         # 控制台路径
        settings:
          web-allow-others: true                          # 允许远程访问控制台



